import "../styles/globals.css"
import "bootstrap/dist/css/bootstrap.min.css"
import { ApolloProvider } from "@apollo/client"
import client from "../apollo"
import Navbar from "../components/Navbar"
import Head from "next/head"

function MyApp({ Component, pageProps }) {
  return (
    <ApolloProvider client={client}>
      <Head>
        <title>Circles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-light min-vh-100">
        <Navbar />
        <div className="container">
          <Component {...pageProps} />
        </div>
      </div>
    </ApolloProvider>
  )
}

export default MyApp
