import "../styles/globals.css"
import "bootstrap/dist/css/bootstrap.min.css"
import { ApolloProvider } from "@apollo/client"
import client from "../apollo"
import Navbar from "../components/Navbar"
import Head from "next/head"
import { useRouter } from "next/router"

function MyApp({ Component, pageProps }) {
  const location = useRouter()
  const isChatPage = location.pathname.endsWith("/chat")

  return (
    <ApolloProvider client={client}>
      <Head>
        <title>Circles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`bg-light p-0 m-0 ${
          isChatPage
            ? "app"
            : "min-vh-100  d-flex flex-column align-items-center"
        }`}
      >
        <Navbar />
        <Component {...pageProps} />
      </div>
    </ApolloProvider>
  )
}

export default MyApp
