import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div style={{ padding: "0 1rem" }}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Circles</h1>
      <nav>
        <Link href="/login">Login/Register</Link>
      </nav>
    </div>
  );
}
